name: NFL Daily Scraper

on:
  schedule:
  - cron: '22 22 * * 4'   # Thursday 6:15 PM ET
  - cron: '45 15 * * 0'   # Sunday 11:45 AM ET
  - cron: '45 18 * * 0'   # Sunday 2:45 PM ET
  - cron: '22 22 * * 0'   # Sunday 6:15 PM ET
  - cron: '22 22 * * 1'   # Monday 6:15 PM ET

  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper script
        run: python nfl/Locks.py

      - name: Commit & push updated data
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "🔁 Auto-update by GitHub Action" || echo "No changes to commit"
          git push
